In [1]:
import numpy as np 

In [2]:
data = np.array([
    [0, 0, 1, 2, 1],
    [0, 0, 3, 0, 1],
    [4, 1, 1, 1, -1],
    [1, 2, 0, 1, -1], 
    [1, 0, 0, 2, -1]
])

In [3]:
data[0, :4]

array([0, 0, 1, 2])

In [8]:
t = 0 
theta = np.zeros(data.shape[1] - 1)
theta_0 = 0

while True: 
    for i in range(data.shape[0]): 
        xt, yt = data[i,:4], data[i,-1]
        t += 1 
        print("Iteration ", t)
        output = xt.dot(theta) + theta_0 
        print(output)
        if output >= 0: 
            h = 1   
        else: 
            h = -1
        if h != yt:
            theta += yt * xt
            theta_0 += yt
            print(f"Updating on iteration {t}")
            print(f"theta {t} = {theta}")
        print(" ")
    if t >= 15: 
        break
    

Iteration  1
0.0
 
Iteration  2
0.0
 
Iteration  3
0.0
Updating on iteration 3
theta 3 = [-4. -1. -1. -1.]
 
Iteration  4
-8.0
 
Iteration  5
-7.0
 
Iteration  6
-4.0
Updating on iteration 6
theta 6 = [-4. -1.  0.  1.]
 
Iteration  7
0.0
 
Iteration  8
-16.0
 
Iteration  9
-5.0
 
Iteration  10
-2.0
 
Iteration  11
2.0
 
Iteration  12
0.0
 
Iteration  13
-16.0
 
Iteration  14
-5.0
 
Iteration  15
-2.0
 


In [5]:
from sklearn.metrics import hinge_loss
import numpy as np

In [6]:
data = np.array([
    [1,1,-1], 
    [3,1,-1],
    [2,3,-1], 
    [2,2,1],
    [3,4,1],
    [4,3,1]
])

In [9]:
x, y = data[:, :2], data[:, -1]
x, y

(array([[1, 1],
        [3, 1],
        [2, 3],
        [2, 2],
        [3, 4],
        [4, 3]]),
 array([-1, -1, -1,  1,  1,  1]))

In [15]:
np.concatenate(1, data[i, :2])

TypeError: dispatcher for __array_function__ did not return an iterable

In [45]:
k = 0 
theta = np.zeros(3)
for i in range(data.shape[0]): 
    x_i, y_i = np.concatenate([[1], data[i, :2]]), data[i, -1]
    if y_i * x_i.dot(theta) <= 1: 
        theta += 1/(k+1) * y_i * x_i
        print("Iteration: ", i+1) 
        print("Theta: ", theta)
        k += 1 
        print("Hinge loss: ", hinge_loss(data[:, -1], theta@np.c_[np.ones(data.shape[0]), data[:, :2]].T))
        print()
    if k == 3: 
        break
    
    
    

Iteration:  1
Theta:  [-1. -1. -1.]
Hinge loss:  4.0

Iteration:  4
Theta:  [-0.5  0.   0. ]
Hinge loss:  1.0

Iteration:  5
Theta:  [-0.16666667  1.          1.33333333]
Hinge loss:  2.527777777777778



In [28]:
np.ones(data.shape[0])

array([1., 1., 1., 1., 1., 1.])

In [36]:
np.c_[np.ones(data.shape[0]), data[:, :2]].shape

(6, 3)